target_sources(parkman PRIVATE
    src/Animation.cpp
    src/Animation.h
    src/Board.cpp
    src/Board.h
	src/Collider.cpp
	src/Collider.h
	src/Controller.cpp
	src/Controller.h
	src/Enemy.cpp
	src/Enemy.h
    src/Game.cpp
    src/Game.h
	src/GUI.cpp
	src/GUI.h
    src/main.cpp
    src/Player.cpp
    src/Player.h
    src/Renderer.cpp
    src/Renderer.h
    src/Texture.cpp
    src/Texture.h
    src/Util.h
)
